<?php include '../../templates/common_start.php'; ?>
<body>
<?php include '../../templates/navbar.php'; ?>
<div id="main_fluid">
  <div id="main_container">
    <div id="left_column">
    
     <?php include'../sidebar.php'; ?>
    <br />
<?php include '../../inc/sidebar.php'; ?>
    </div>
    <div id="two_column">
 
<div class="rounded">
          <h1 class="title-head-right">Sponsor Us</h1>
<p>Edge Radio would not be able to keep broadcasting without the generous support of our sponsors. We rely on sponsorship from businesses and organisations as well as supporter donations to bring you great content.</p>
          
<p>34% (58,000) of Hobart listens to community radio every week!</p>
   
<p>Edge Radio will deliver your message to a new audience. We offer a variety of shows to target alternative markets, you’re message is sure to stand out with only 5 minutes of sponsorship announcements an hour!</p>

<p>Edge listeners are active listeners who are engaged in the local community. We’ll script and produce all of your sponsorship announcements.</p>

<p>Edge is an independent, not-for-profit broadcaster generated by the community for the community. We support local music, arts and culture 24/7!</p>

<p>Edge Radio is active in the community - we go places others wouldn’t even dream of! Bringing you Live Broadcasts, interviews and the latest news from all sorts of events! You’ll be supporting a not-for-profit, charitable organisation in your community. Edge is generated by the community for the community. Independent radio offers you an alternative.</p>

<p>Radio advertising works!</p>
          
<p>If you would like to support the station by taking out an on air campaign, please contact the Sponsorship and Promotions Team.</p>

<p>They can be reached on 03 6226 7273 or email sponsor@edgeradio.org.au</p>
</div>
   
        
      <div id="footer">
        <?php include '../../templates/footer.php'; ?>
      </div>
    </div>
  </div>
</div>
<?php include '../../templates/common_end.php'; ?>
