<?php

/*
 * phpMyEdit language file
 *
 * language: polish
 * encoding: iso-8859-2
 * date: 01/10/2002, 30/06/2003
 * author: Piotr Walesiuk <p.walesiuk@bos.com.pl>
 */

/* $Platon: phpMyEdit/lang/PME.lang.PL.inc,v 1.8 2004/01/12 05:52:56 nepto Exp $ */

return Array(
		'Add'          	=>'Dodaj',
		'Copy'         	=>'Kopiuj',
		'Change'       	=>'Zmieñ',
		'Delete'       	=>'Usuñ',
		'View'      	=>'Poka¿',
		'Prev'         	=>'Wstecz',
		'Next'         	=>'Dalej',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'         	=>'Strona',
		'Records'      	=>'Rekordy',
		'Save'          =>'Zapisz',
		'More'          =>'Wiêcej',
		'Apply'         =>'Zastosuj',
		'Cancel'        =>'Anuluj',
		'Search'	=>'Szukaj',
		'Hide'		=>'Ukryj',
		'Clear'		=>'Wyczy¶æ',
		'Query'		=>'Zapytanie',
		'Current Query'	=>'Aktualne zapytanie',
		'Sorted By'		=>'Posortowane wed³ug',
		'ascending'		=>'rosn±co',
		'descending'	=>'malej±co',
		'hidden'		=>'ukryte',
		'of'            =>'z',
		'record added'  =>'rekord dodany',
		'record changed'=>'rekord zmieniony',
		'record deleted'=>'rekord usuniêty',
		'Please enter'  =>'Proszê wprowadziæ',
		'months'	=> Array(
			'01'=>'Styczeñ',
			'02'=>'Luty',
			'03'=>'Marzec',
			'04'=>'Kwiecieñ',
			'05'=>'Maj',
			'06'=>'Czerwiec',
			'07'=>'Lipiec',
			'08'=>'Sierpieñ',
			'09'=>'Wrzesieñ',
			'10'=>'Pa¼dziernik',
			'11'=>'Listopad',
			'12'=>'Grudzieñ')
		);

?>
