<?php

/*
 * phpMyEdit language file
 *
 * language: italian (standard)
 * encoding: iso-8859-1
 * date: 02/2002, 7/11/2002, 13/4/2003
 * authors:
 *   Dario <dartar@users.sourceforge.net>
 *   Keatch <spangarox@yahoo.it>
 */

/* $Platon: phpMyEdit/lang/PME.lang.IT.inc,v 1.13 2004/01/12 05:52:56 nepto Exp $ */

return Array(
		'Add'           =>'Aggiungi',
		'Copy'          =>'Copia',
		'Change'        =>'Modifica',
		'Delete'        =>'Cancella',
		'View'      	=>'Visualizza',
		'Prev'          =>'Precedente',
		'Next'          =>'Seguente',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'          =>'Pagina',
		'Records'       =>'Voci',
		'Save'          =>'Salva',
		'More'          =>'Salva & Continua',
		'Apply'         =>'Applica', 
		'Cancel'        =>'Annulla',
		'Search'        =>'Cerca',
		'Hide'          =>'Nascondi',
		'Clear'         =>'Svuota',
		'Query'         =>'Chiedi',	
		'Current Query'	=>'Richiesta Corrente', 
		'Sorted By'     =>'Ordinato per',
		'ascending'     =>'crescente',
		'descending'    =>'decrescente',
		'hidden'        =>'nascosto',
		'of'            =>'/',		
		'record added'  =>'voce aggiunta',
		'record changed'=>'voce modificata',
		'record deleted'=>'voce eliminata',
		'Please enter'  =>'Si prega di riempire il campo: ',
		'months'	=> Array(
			'01'=>'Gennaio',
			'02'=>'Febbraio',
			'03'=>'Marzo',
			'04'=>'Aprile',
			'05'=>'Maggio',
			'06'=>'Giugno',
			'07'=>'Luglio',
			'08'=>'Agosto',
			'09'=>'Settembre',
			'10'=>'Ottobre',
			'11'=>'Novembre',
			'12'=>'Dicembre'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
