<?php

/*
 * phpMyEdit language file
 *
 * language: danish
 * encoding: iso-8859-1
 * date: 19/3/2003
 * author: Henrik Nielsen <kontakt@innovapage.dk>
 */

/* $Platon: phpMyEdit/lang/PME.lang.DK.inc,v 1.4 2004/01/12 05:52:56 nepto Exp $ */

return Array(
		'Add'           	=>'Tilføj',
		'Copy'           	=>'Kopier',
		'Change'        	=>'Ret',
		'Delete'        	=>'Slet',
		'View'  	   		=>'Se',
		'Prev'          	=>'Tilbage',
		'Next'          	=>'Næste',
		'First'         	=>'First', // untranslated
		'Last'          	=>'Last',  // untranslated
		'Go to'         	=>'Go to', // untranslated
		'Page'          	=>'Side',
		'Records'       	=>'Rækker',
		'Save'          	=>'Gem',
		'More'          	=>'Mere',
		'Apply'         	=>'Tilføj',
		'Cancel'        	=>'Fortryd',
		'Search'			=>'Søg',
		'Hide'				=>'Skjul',
		'Clear'				=>'Tøm',
		'Query'				=>'Søg',
		'Current Query'		=>'Current Query', // untranslated
		'Sorted By'			=>'Sorted By',     // untranslated
		'ascending'			=>'ascending',     // untranslated
		'descending'		=>'descending',    // untranslated
		'hidden'			=>'hidden',        // untranslated
		'of'				=>'af',
		'record added'  	=>'række tilføjet',
		'record changed'	=>'række ændret',
		'record deleted'	=>'række slettet',
		'Please enter'  	=>'Indtast venligst',
		'months' => Array(
				'01'=>'Januar',
				'02'=>'Februar',
				'03'=>'Marts',
				'04'=>'April',
				'05'=>'Maj',
				'06'=>'Juni',
				'07'=>'Juli',
				'08'=>'August',
				'09'=>'September',
				'10'=>'Oktober',
				'11'=>'November',
				'12'=>'December'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);
		
?>
