<?php

/*
 * phpMyEdit language file
 *
 * language: swedish
 * encoding: iso-8859-1
 * date: 21/01/2004, 07/02/2004
 * authors:
 *   Björn Hammarbäck <bjorn@hammarback.se>
 *   Stefan Lindmark <stefan@lindmark.net>
 */

/* $Platon: phpMyEdit/lang/PME.lang.SE.inc,v 1.3 2004/02/09 12:22:15 nepto Exp $ */

/*
 *    å = &aring;
 *    ä = &auml;
 *    ö = &ouml;
 *    Ä = &Auml;
 */

return Array(
		'Add'           	=>'Lägg till',
		'Copy'           	=>'Kopiera',
		'Change'        	=>'Ändra',
		'Delete'        	=>'Ta bort',
		'View'  	   		=>'Visa detaljer',
		'Prev'          	=>'Föregående',
		'Next'          	=>'Nästa',
		'First'         	=>'Första',
		'Last'          	=>'Sista',
		'Go to'         	=>'Gå till sida',
		'Page'          	=>'Sida',
		'Records'       	=>'Poster',
		'Save'          	=>'Spara',
		'More'          	=>'Mer',
		'Apply'         	=>'Verkställ',
		'Cancel'        	=>'Avbryt',
		'Search'			=>'Sök',
		'Hide'			=>'Dölj',
		'Clear'			=>'Rensa',
		'Query'			=>'Sök',
		'Current Query'		=>'Nuvarande fråga',
		'Sorted By'			=>'Sorterad efter',
		'ascending'			=>'stigande',
		'descending'		=>'fallande',
		'hidden'			=>'gömd',
		'of'				=>'av',
		'record added'  	=>'post adderad',
		'record changed'	=>'post ändrad',
		'record deleted'	=>'post borttagen',
		'Please enter'  	=>'Fyll i fältet',
		'months' => Array(
				'01'=>'Januari',
				'02'=>'Februari',
				'03'=>'Mars',
				'04'=>'April',
				'05'=>'Maj',
				'06'=>'Juni',
				'07'=>'Juli',
				'08'=>'Augusti',
				'09'=>'September',
				'10'=>'Oktober',
				'11'=>'November',
				'12'=>'December'),
		// phpMyEdit-report
		'Make report'			=> 'Skapa rapport',
		'Select fields'			=> 'Välj fält',
		'Records per screen'	=> 'Poster per skärm',
		);
		
?>
