<?php

/*
 * phpMyEdit language file
 *
 * language: portuguese (standard)
 * encoding: iso-8859-1
 * date: 02/2002
 * author: unknown
 */

/* $Platon: phpMyEdit/lang/PME.lang.PT.inc,v 1.4 2004/01/12 05:52:56 nepto Exp $ */

return Array(
		'Add'           =>'Adicione',
		'Copy'         	=>'Cópia',
		'Change'        =>'Mude',
		'Delete'        =>'Suprima',
		'View'      	=>'Indicador',
		'Prev'          =>'Precedente',
		'Next'          =>'Seguinte',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'          =>'Página',
		'Records'       =>'Registros',
		'Save'          =>'Excepto',
		'More'          =>'Mais',
		'Apply'         =>'Apply', // untranslated
		'Cancel'        =>'cancelamento',
		// Translate and uncomment
		//'Search'		=>'Search',
		//'Hide'		=>'Hide',
		//'Clear'		=>'Clear',
		//'Query'		=>'Query',
		'Current Query'	=>'Current Query', // untranslated
		'Sorted By'		=>'Sorted By', // untranslated
		'ascending'		=>'ascending', // untranslated
		'descending'	=>'descending',// untranslated
		'hidden'		=>'hidden',    // untranslated
		'of'			=>'/', // untranslated
		'record added'  =>'suprimido mudado',
		'record changed'=>'Record adicionado',
		'record deleted'=>'Record record',
		'Please enter'  =>'Por favor entram ',
		'months' =>	Array(
			'01'=>'Janeiro',
			'02'=>'Fevereiro',
			'03'=>'Março',
			'04'=>'Abril',
			'05'=>'Pode',
			'06'=>'Junho',
			'07'=>'Julho',
			'08'=>'Agosto',
			'09'=>'Setembro',
			'10'=>'Outubro',
			'11'=>'Novembro',
			'12'=>'Dezembro'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
