<?php

/*
 * phpMyEdit language file
 *
 * language: spanish
 * encoding: iso-8859-1
 * date: 02/2003, 22/04/2003
 * author: Jorge Nadal <jornamon@ya.com>
 */

/* $Platon: phpMyEdit/lang/PME.lang.ES.inc,v 1.4 2004/01/12 05:52:56 nepto Exp $ */

return Array(
		'Add'           =>'Agregar',
		'Copy'         	=>'Copiar',
		'Change'        =>'Cambiar',
		'Delete'        =>'Suprimir',
		'View'      	=>'Visualizar',
		'Prev'          =>'Anterior',
		'Next'          =>'Siguiente',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'          =>'Página',
		'Records'       =>'Registros',
		'Save'          =>'Grabar',
		'More'          =>'Más',
		'Apply'         =>'Aplicar',
		'Cancel'        =>'Cancelar',
		'Search'		=>'Buscar',
		'Hide'			=>'Ocultar',
		'Clear'			=>'Limpiar',
		'Query'			=>'Consultar',
		'Current Query'	=>'Consulta actual',
		'Sorted By'		=>'Ordenado por',
		'ascending'		=>'ascendente',
		'descending'	=>'descendente',
		'hidden'		=>'oculto',
		'of'			=>'de',
		'record added'  =>'Registro añadido',
		'record changed'=>'Registro cambiado',
		'record deleted'=>'Registro borrado',
		'Please enter'  =>'Por favor introduzca ',
		'months'	=> Array(
			'01'=>'Enero',
			'02'=>'Febrero',
			'03'=>'Marzo',
			'04'=>'Abril',
			'05'=>'Mayo',
			'06'=>'Junio',
			'07'=>'Julio',
			'08'=>'Agosto',
			'09'=>'Septiembre',
			'10'=>'Octubre',
			'11'=>'Noviembre',
			'12'=>'Diciembre'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
