<?php

/*
 * phpMyEdit language file
 *
 * language: turkish
 * encoding: iso-8859-9
 * date: 24/10/2003
 * author: Nuri Akman <nuri.akman@hazine.gov.tr>
 */

/* $Platon: phpMyEdit/lang/PME.lang.TR.inc,v 1.2 2004/01/12 05:52:56 nepto Exp $ */

return Array(
		'Add'           	=>'Ekle',
		'Copy'           	=>'Kopyala',
		'Change'        	=>'Düzenle',
		'Delete'        	=>'Sil',
		'View'  	   	 	=>'Gör',
		'Prev'          	=>'Önceki',
		'Next'          	=>'Sonraki',
		'First'         =>'First', // untranslated
		'Last'          =>'Last',  // untranslated
		'Go to'         =>'Go to', // untranslated
		'Page'          	=>'Sayfa',
		'Records'       	=>'Kayýt',
		'Save'          	=>'Kaydet',
		'More'          	=>'Sonrasý',
		'Apply'         	=>'Uygula',
		'Cancel'        	=>'Vazgeç',
		'Search'			=>'Ara',
		'Hide'				=>'Gizle',
		'Clear'				=>'Temizle',
		'Query'				=>'Sorgu',
		'Current Query'		=>'Aktif Sorgu',
		'Sorted By'			=>'Sýralama',
		'ascending'			=>'artan',
		'descending'		=>'azalan',
		'hidden'			=>'gizli',
		'of'				=>' / ',
		'record added'  	=>'kayýt eklendi',
		'record changed'	=>'kayýt deðiþtirildi',
		'record deleted'	=>'kayýt silindi',
		'Please enter'  	=>'Lütfen giriniz :',
		'months' => Array(
			'01'=>'Ocak',
			'02'=>'Þubat',
			'03'=>'Mart',
			'04'=>'Nisan',
			'05'=>'Mayýs',
			'06'=>'Haziran',
			'07'=>'Temmuz',
			'08'=>'Auðustos',
			'09'=>'Eylül',
			'10'=>'Ekim',
			'11'=>'Kasým',
			'12'=>'Aralýk'),
		// phpMyEdit-report
		'Make report'			=> 'Make report',
		'Select fields'			=> 'Select fields',
		'Records per screen'	=> 'Records per screen',
		);

?>
