<?php

/*
 * phpMyEdit language file
 *
 * language: dutch (standard)
 * encoding: iso-8859-1
 * date: 21/09/2002, 17/12/2002
 * authors:
 *   Paul Barends <pbarends@xs4all.nl>
 *   Erwin Janszen <Erwin.Janszen@mail.ing.nl>
 */

/* $Platon: phpMyEdit/lang/PME.lang.NL.inc,v 1.14 2004/01/21 16:43:55 nepto Exp $ */

return Array(
		'Add'               =>'Toevoegen',
		'Copy'              =>'Copiëren',
		'Change'            =>'Bewerken',
		'Delete'            =>'Wissen',
		'View'              =>'Details',
		'Prev'              =>'Vorige',
		'Next'              =>'Volgende',
		'First'         	=>'Eerste',
		'Last'          	=>'Laaste',
		'Go to'         	=>'Ga naar',
		'Page'              =>'Pagina',
		'Records'           =>'Rijen',
		'Save'              =>'Bewaren',
		'More'              =>'Meer',
		'Apply'             =>'Toepassen',
		'Cancel'            =>'Annuleren',
		'Search'            =>'Zoeken',
		'Hide'              =>'Verbergen',
		'Clear'             =>'Schonen',	// 'Leeg maken',
		'Query'             =>'Selecteer',	// 'Selectie maken',
		'Current Query'     =>'Huidige selectie',
		'Sorted By'         =>'Gesorteerd op',
		'ascending'         =>'oplopend',
		'descending'        =>'aflopend',
		'hidden'            =>'verborgen',
		'of'                =>'van',
		'record added'      =>'rij toegevoegd',
		'record changed'    =>'rij aangepast',
		'record deleted'    =>'rij gewist',
		'Please enter'      =>'Voer a.u.b. in:',
		'months' => Array(
			'01'=>'januari',
			'02'=>'februari',
			'03'=>'maart',
			'04'=>'april',
			'05'=>'mei',
			'06'=>'juni',
			'07'=>'juli',
			'08'=>'augustus',
			'09'=>'september',
			'10'=>'october',
			'11'=>'november',
			'12'=>'december'),
		// phpMyEdit-report
		'Make report'			=> 'Maak rapport',
		'Select fields'			=> 'Selecteer velden',
		'Records per screen'	=> 'Rij per scherm',
		);

?>
