<?php

/*
 * phpMyEdit language file
 *
 * language: portuguese (brazilian)
 * encoding: iso-8859-1
 * date: 23/12/2002, 14/1/2003, 17/5/2003, 21/1/2004
 * author: Roberto Cohen <roberto.cohen@fireman.com.br>
 */

/* $Platon: phpMyEdit/lang/PME.lang.PT-BR.inc,v 1.7 2004/01/21 16:42:48 nepto Exp $ */

return Array(
		'Add'           =>'Adiciona',
		'Copy'          =>'Copia',
		'Change'        =>'Edita',
		'Delete'        =>'Remove',
		'View'       	=>'Visualiza',
		'Prev'          =>'Anterior',
		'Next'          =>'Próximo',
		'First'         =>'Primeiro', 
		'Last'          =>'Último',  
		'Go to'         =>'Vai para', 
		'Page'          =>'Página',
		'Records'       =>'Registros',
		'Save'          =>'Salva',
		'More'          =>'Mais',
		'Apply'         =>'Aplica',
		'Cancel'        =>'Cancela',
		'Search'		=>'Pesquisa',
		'Hide'			=>'Esconde',
		'Clear'			=>'Limpa',
		'Query'			=>'Resultado',
		'Current Query'	=>'Resultado atual',
		'Sorted By'		=>'Ordernado por',
		'ascending'		=>'crescente',
		'descending'	=>'descendente',
		'hidden'		=>'escondido',
		'of'			=>'de',
		'record added'  =>'registro adicionado',
		'record changed'=>'registro editado',
		'record deleted'=>'registro removido',
		'Please enter'  =>'Por favor, entre',
		'months' =>	Array(
				'01'=>'Janeiro',
				'02'=>'Fevereiro',
				'03'=>'Março',
				'04'=>'Abril',
				'05'=>'Maio',
				'06'=>'Junho',
				'07'=>'Julho',
				'08'=>'Agosto',
				'09'=>'Setembro',
				'10'=>'Outubro',
				'11'=>'Novembro',
				'12'=>'Dezembro'),
		// phpMyEdit-report
		'Gerar relatório'			=> 'Make report',
		'Selecionar campos'			=> 'Select fields',
		'Registros por tela'	=> 'Records per screen',
		);

?>
